flexform/urls.py
from django.urls import path
from django.views.generic import RedirectView
from django.conf.urls import url, include
from rest_framework import routers
from . import views
from django.conf import settings
from django.conf.urls.static import static

router = routers.DefaultRouter()
#router.register(r'form',views.FormViewSet)
#router.register(r'object',views.ObjectViewSet)
#router.register(r'member',views.FormMemberViewSet)
#router.register(r'result',views.ResultViewSet)
router.register(r'flexform',views.FlexFormGetViewGet)
#router.register(r'set',views.FlexFormSetViewSet)
#router.register(r'set',views.send_object, basename='send_object')
urlpatterns = [
    url(r'^', include (router.urls)),
    url(r'^favicon\.ico$',RedirectView.as_view(url='static/images/favicon.ico')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

setup/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.urls import path
from flexform import urls, views
from django.views.generic import RedirectView
from django.conf import settings
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/', include('flexform.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    #path('', include('flexform.urls')),
    path('', views.Index.as_view(), name='index'),
    path('forms_page/', views.Forms.as_view(), name='forms_page'),
    path('developer/', views.Developer.as_view(), name='developer'),
    path('forms/', views.forms, name='forms'),
    path('objects/', views.objects, name='objects'),
    path('api/insert', views.send_object, name='insert'),
    path('api/update', views.update_object, name='update'),
    path('api/delete', views.delete_object, name='detele'),
    path('open_form/', views.open_form, name='open_form'),
    path('open_list/', views.open_list, name='open_list'),
    path('create_form/', views.FormCreateView.as_view(), name='create_form'),
    path('update_form/<int:pk>', views.FormUpdateView.as_view(), name='update_form'),
    path('read_form/<int:pk>', views.FormReadView.as_view(), name='read_form'),
    path('delete_form/<int:pk>', views.FormDeleteView.as_view(), name='delete_form'),
    path('create_member/<int:pk>', views.MemberCreateView.as_view(), name='create_member'),
    path('read_member/<int:pk>', views.MemberReadView.as_view(), name='read_member'),
    path('update_member/<int:pk>', views.MemberUpdateView.as_view(), name='update_member'),
    path('delete_member/<int:pk>', views.MemberDeleteView.as_view(), name='delete_member'),
    path('create_object/<int:pk>', views.ObjectCreateView.as_view(), name='create_object'),
    path('update_object/<int:pk>', views.ObjectUpdateView.as_view(), name='update_object'),
    path('read_object/<int:pk>', views.ObjectReadView.as_view(), name='read_object'),
    path('delete_object/<int:pk>', views.ObjectDeleteView.as_view(), name='delete_object'),
    path('filter/', views.BookFilterView.as_view(), name='filter_book'),
    path('create/', views.BookCreateView.as_view(), name='create_book'),
    path('update/<int:pk>', views.BookUpdateView.as_view(), name='update_book'),
    path('read/<int:pk>', views.BookReadView.as_view(), name='read_book'),
    path('delete/<int:pk>', views.BookDeleteView.as_view(), name='delete_book'),
    path('books/', views.books, name='books'),
    path('signup/', views.SignUpView.as_view(), name='signup'),
    path('login/', views.CustomLoginView.as_view(), name='login'),
    url(r'^favicon\.ico$',RedirectView.as_view(url='static/images/favicon.ico')),


] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

flexform/models.py
from django.db import models
from django.contrib.auth.models import User

class Book(models.Model):
    HARDCOVER = 1
    PAPERBACK = 2
    EBOOK = 3
    BOOK_TYPES = (
        (HARDCOVER, 'Hardcover'),
        (PAPERBACK, 'Paperback'),
        (EBOOK, 'E-book'),
    )
    title = models.CharField(max_length=50)
    publication_date = models.DateField(null=True)
    author = models.CharField(max_length=30, blank=True)
    price = models.DecimalField(max_digits=5, decimal_places=2)
    pages = models.IntegerField(blank=True, null=True)
    book_type = models.PositiveSmallIntegerField(choices=BOOK_TYPES)

    timestamp = models.DateField(auto_now_add=True, auto_now=False)

class Form(models.Model):
    title = models.CharField(max_length=50)
    status = models.BooleanField(default=True)
    private = models.BooleanField(default=True)
    created_by = models.ForeignKey(User, on_delete=models.CASCADE,null=True)
    timestamp = models.DateField(auto_now_add=True, auto_now=False)

    def __str__(self):
        return self.title


class FormMember(models.Model):
    ADMIN = 1
    MEMBER = 2
    OBJECT_TYPES = (
        (ADMIN, 'Admin'),
        (MEMBER, 'Member'),
    )
    form = models.ForeignKey('form', related_name='member', on_delete=models.CASCADE)
    role = models.PositiveSmallIntegerField(choices=OBJECT_TYPES)
    user = models.ForeignKey(User, on_delete=models.CASCADE,null=True)

    def __str__(self):
        if self.user is not None:
            return str(self.user.username) + ':' + str(self.role)
        else:
            return ''

class Object(models.Model):
    STRING = 1
    NUMBER = 2
    IMAGE = 3
    OBJECT_TYPES = (
        (STRING, 'String'),
        (NUMBER, 'Number'),
        (IMAGE, 'Image'),
    )
    form = models.ForeignKey('form', related_name='object', on_delete=models.CASCADE)
    label = models.CharField(max_length=50)
    description = models.CharField(max_length=100, default="",  blank = True)
    type = models.PositiveSmallIntegerField(choices=OBJECT_TYPES)
    created_by = models.ForeignKey(User, on_delete=models.CASCADE,null=True)
    timestamp = models.DateField(auto_now_add=True, auto_now=False)
    def __str__(self):
        return self.label

class IdResult(models.Model):
    form = models.ForeignKey('form', related_name='response', on_delete=models.CASCADE)

    def __str__(self):
        if self.id is not None:
            return str(self.id)
        else:
            return ''



class Result(models.Model):
    form = models.ForeignKey('form', on_delete=models.CASCADE)
    object = models.ForeignKey('object', on_delete=models.CASCADE)
    id_result = models.ForeignKey('idresult', related_name='response_detail', on_delete=models.CASCADE)
    value = models.CharField(max_length=50)
    image = models.ImageField(upload_to='uploads/images')
    created_by = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    timestamp = models.DateField(auto_now_add=True, auto_now=False)

    @property
    def image_url(self):
        if self.image and hasattr(self.image, 'url'):
            return self.image.url

flexform/views.py
from django.http import JsonResponse
from django.shortcuts import render
from django.template.loader import render_to_string
from django.contrib.messages.views import SuccessMessageMixin
from django.urls import reverse_lazy
from django.views import generic
from django.http import HttpResponseRedirect
import json
from django.http import JsonResponse
from django.core import serializers
from django.db.models import Case, When
from .serializer import FormSerializer, ObjectSerializer, FormMemberSerializer, ResultSerializer, FlexFormGetSerializer, FlexFormSetSerializer
from rest_framework import viewsets
from django.contrib.auth.models import User
from rest_framework.response import Response
from django.shortcuts import get_object_or_404
from rest_framework.decorators import api_view
from rest_framework import status
from django.views.decorators.csrf import csrf_exempt
from django.http import HttpResponse
from django.contrib.auth import authenticate, login
from basicauth import decode

from bootstrap_modal_forms.generic import (
    BSModalLoginView,
    BSModalFormView,
    BSModalCreateView,
    BSModalUpdateView,
    BSModalReadView,
    BSModalDeleteView
)

from .forms import (
    BookModelForm,
    CustomUserCreationForm,
    CustomAuthenticationForm,
    BookFilterForm,
    FormModelForm,
    ObjectModelForm,
    OpenModelForm,
    FormMemberModelForm,
    UpdateFormMemberModelForm
)
from .models import Book, Form, Object, Result, IdResult, FormMember

class FormViewSet(viewsets.ModelViewSet):
    queryset = Form.objects.all()
    serializer_class = FormSerializer

    def perform_create(self, serializer):
        serializer.save(created_by=self.request.user)

class ObjectViewSet(viewsets.ModelViewSet):
    queryset = Object.objects.all()
    serializer_class = ObjectSerializer
    def perform_create(self, serializer):
        serializer.save(created_by=self.request.user)

class FormMemberViewSet(viewsets.ModelViewSet):
    queryset = FormMember.objects.all()
    serializer_class = FormMemberSerializer

class ResultViewSet(viewsets.ModelViewSet):
    queryset = Result.objects.all()
    serializer_class = ResultSerializer

    def perform_create(self, serializer):
        IdResult.objects.create(form=Form.objects.filter(id=serializer.validated_data['form'].id).first())
        id_result = IdResult.objects.filter().last()
        serializer.save(id_result=id_result)

class FlexFormGetViewGet(viewsets.ModelViewSet):
    queryset = Form.objects.none()
    model = Form
    serializer_class = FlexFormGetSerializer
    def get_queryset(self):
        if self.request.user.is_superuser:
            return Form.objects.all().order_by('id')
        elif self.request.user.is_authenticated:
            form_members = FormMember.objects.filter(user=self.request.user).values_list('form')
            return Form.objects.filter(created_by=self.request.user) | \
                   Form.objects.filter(private=False) | \
                   Form.objects.filter(id__in=form_members).order_by('id')
        else:
            return Form.objects.filter(private=False).order_by('id')

class FlexFormSetViewSet(viewsets.ModelViewSet):
    queryset = Object.objects.all()
    model = Object
    serializer_class = FlexFormSetSerializer


@csrf_exempt
def send_object(request):
    encoded_str = request.headers['Authorization']
    username, password = decode(encoded_str)
    user = authenticate(request, username=username, password=password)
    if user is not None:
        login(request, user)
    else:
        return HttpResponse(" Unauthorized")
    if request.method == 'POST':
        form_id = request.GET.get("form_id", '') or ''
        if form_id == '':
            return HttpResponse("Missing form_id parameter")
        else:

            if user.is_superuser:
                form_selected = Form.objects.filter(id=form_id)
            elif user.is_authenticated:
                form_members = FormMember.objects.filter(user=user).values_list('form')
                form_selected = Form.objects.filter(id=form_id, created_by=user) | \
                       Form.objects.filter(id=form_id, private=False) | \
                       Form.objects.filter(id=form_id).filter(id__in=form_members)
            else:
                form_selected = Form.objects.filter(private=False)

            #form_selected = Form.objects.filter(id__in=form_id) # without auth filter

            if form_selected:
                objects = Object.objects.filter(form__in=form_selected)
                parameters=[]
                values=[]
                if objects:
                    count=0
                    for object in objects:
                        parameters.insert(count, object.label.lower())
                        if request.GET.get(parameters[count]) == '' and object.type is not 3:
                            return HttpResponse('Parameter ' + parameters[count] + ' is empty')
                        elif request.GET.get(parameters[count]) == None:
                            return HttpResponse("Missing " + parameters[count] + ' as parameter')
                        else:
                            if object.type == 2:
                                string_int = request.GET.get(parameters[count])
                                try:
                                    string_int = float(request.GET.get(parameters[count]))
                                except ValueError:
                                    print('Please enter an integer')
                                if is_integer_num(string_int):
                                    values.insert(count, request.GET.get(parameters[count]))
                                    count += 1
                                else:
                                    return HttpResponse('Parameter ' + parameters[count] + ' is not a number')
                            elif object.type == 3:
                                values.insert(count, request.FILES.get(parameters[count]))
                            else:
                                values.insert(count, request.GET.get(parameters[count]))
                                count += 1
                    countparam = 0
                    IdResult.objects.create(form=form_selected.last()).form
                    id_result = IdResult.objects.filter().last()

                    for object in objects:
                        if object.type == 3:
                            Result.objects.create(form=form_selected.last(), object=object, id_result=id_result,
                                                  image=values[countparam], created_by=request.user)
                        else:
                            Result.objects.create(form=form_selected.last(), object=object, id_result=id_result,
                                                  value=values[countparam], created_by=request.user)
                        countparam += 1
                    return HttpResponse("Objects was sent")

                else:
                    return HttpResponse("No objects in this instance")
            else:
                return HttpResponse("Parameter form_id not found or you don't have permission to access this instance.\nPlease access ../api/flexform to check the instance information")

@csrf_exempt
def update_object(request):
    encoded_str = request.headers['Authorization']
    username, password = decode(encoded_str)
    user = authenticate(request, username=username, password=password)
    if user is not None:
        login(request, user)
    else:
        return HttpResponse(" Unauthorized")
    if request.method == 'POST':
        form_id = request.GET.get("form_id", '') or ''
        id_result = request.GET.get('id_response', '') or ''
        if form_id == '':
            return HttpResponse("Missing form_id parameter")
        elif id_result == '':
            return HttpResponse("Missing id_response parameter")
        else:
            if user.is_superuser:
                form_selected = Form.objects.filter(id=form_id)
            elif user.is_authenticated:
                form_members = FormMember.objects.filter(user=user).values_list('form')
                form_selected = Form.objects.filter(id=form_id, created_by=user) | \
                       Form.objects.filter(id=form_id, private=False) | \
                       Form.objects.filter(id=form_id).filter(id__in=form_members)
            else:
                form_selected = Form.objects.filter(private=False)

            if form_selected:
                print(form_selected)
                objects = Object.objects.filter(form__in=form_selected)
                parameters=[]
                values=[]
                form_filled = Result.objects.filter(form=form_selected.first(), id_result=IdResult.objects.filter(id=id_result).last())
                if form_filled.count() == 0:
                    return HttpResponse("id_response does not exist")
                if objects:
                    count=0
                    for object in objects:
                        parameters.insert(count, object.label.lower())
                        if request.GET.get(parameters[count]) == '' and object.type is not 3:
                            return HttpResponse('Parameter ' + parameters[count] + ' is empty')
                        elif request.GET.get(parameters[count]) == None:
                            print("Nothing to do with "+parameters[count]+" parameter")
                        else:
                            if object.type == 2:
                                string_int = request.GET.get(parameters[count])
                                try:
                                    string_int = float(request.GET.get(parameters[count]))
                                except ValueError:
                                    print('Please enter an integer')

                                if is_integer_num(string_int):

flexform/templates/flexform/create_form.html
{% load widget_tweaks %}
{% load crispy_forms_tags %}
{% load i18n %}
<form method="post" action="">
  {% csrf_token %}
  <div class="modal-header">
    <h3 class="modal-title">{% trans 'Create' %} {% trans 'Instance' %}</h3>
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>

  <div class="modal-body">

    <div class="{% if form.non_field_errors %}invalid{% endif %} mb-2">
      {% for error in form.non_field_errors %}
        {{ error }}
      {% endfor %}
    </div>
    {% crispy form %}
    <div class="{% if form.errors %} invalid{% endif %}">
          {% for error in form.errors %}
            <!--p class="help-block">{{ error }}</p-->
          {% endfor %}
    </div>
    <!--{% for field in form %}
      <div class="form-group">
        <label for="{{ field.id_for_label }}">{{ field.label }}</label>
        {% render_field field class="form-control" placeholder=field.label %}
        <div class="{% if field.errors %} invalid{% endif %}">
          {% for error in field.errors %}
            <p class="help-block">{{ error }}</p>
          {% endfor %}
        </div>
      </div>
    {% endfor %}-->
  </div>

  <div class="modal-footer">
    <button type="button" class="submit-btn btn btn-secondary"  style="background-color: #90323D;">{% trans 'Create' %}</button>
  </div>

</form>

flexform/templates/flexform/create_member.html
{% load widget_tweaks %}
{% load crispy_forms_tags %}
{% load i18n %}
<form method="post" action="">
  {% csrf_token %}

  <div class="modal-header">
    <h3 class="modal-title">{% trans 'Add' %} {% trans 'Member' %}</h3>
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>

  <div class="modal-body">

    <div class="{% if form.non_field_errors %}invalid{% endif %} mb-2">
      {% for error in form.non_field_errors %}
        {{ error }}
      {% endfor %}
    </div>
    {% crispy form %}
    <div class="{% if form.errors %} invalid{% endif %}">
          {% for error in form.errors %}
            <!--p class="help-block">{{ error }}</p-->
          {% endfor %}
    </div>
    <!--
    {% for field in form %}
      <div class="form-group">
        <label for="{{ field.id_for_label }}">{{ field.label }}</label>
        {% render_field field class="form-control" placeholder=field.label %}
        <div class="{% if field.errors %} invalid{% endif %}">
          {% for error in field.errors %}
            <p class="help-block">{{ error }}</p>
          {% endfor %}
        </div>
      </div>
    {% endfor %}-->
  </div>

  <div class="modal-footer">
    <button type="button" class="submit-btn btn btn-secondary"  style="background-color: #393e46;">{% trans 'Add' %}</button>
  </div>

</form>

flexform/templates/flexform/delete_book.html
{% load widget_tweaks %}

<form method="post" action="">
  {% csrf_token %}

  <div class="modal-header">
    <h3 class="modal-title">Delete Book</h3>
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>

  <div class="modal-body">
    <p class="delete-text">Are you sure you want to delete book with title
      <strong>{{ book.title }}</strong>?</p>
  </div>

  <div class="modal-footer">
    <button type="submit" id="delete-btn" class="btn btn-danger">Delete</button>
  </div>

</form>

flexform/templates/flexform/delete_form.html
{% load widget_tweaks %}
{% load i18n %}
<form method="post" action="">
  {% csrf_token %}

  <div class="modal-header">
    <h3 class="modal-title">{% trans 'Delete' %} {% trans 'Instance' %}</h3>
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>

  <div class="modal-body">
    <p class="delete-text">{% trans 'Are you sure you want to delete instance with name' %}
      <strong>{{ form.title }}</strong>?</p>
  </div>

  <div class="modal-footer">
    <button type="submit" id="delete-btn" class="btn btn-danger">{% trans 'Delete' %}</button>
  </div>

</form>

flexform/templates/flexform/delete_member.html
{% load widget_tweaks %}
{% load i18n %}
<form method="post" action="">
  {% csrf_token %}

  <div class="modal-header">
    <h3 class="modal-title">{% trans 'Delete' %} {% trans 'Member' %}</h3>
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>

  <div class="modal-body">
    <p class="delete-text">{% trans 'Are you sure you want to remove  ' %}
      <strong>{{ formmember.user }}</strong>?</p>
  </div>

  <div class="modal-footer">
    <button type="submit" id="delete-btn" class="btn btn-danger">{% trans 'Remove' %}</button>
  </div>

</form>

flexform/templates/flexform/delete_object.html
{% load widget_tweaks %}
{% load i18n %}
<form method="post" action="">
  {% csrf_token %}

  <div class="modal-header">
    <h3 class="modal-title">{% trans 'Delete' %} {% trans 'Object' %}</h3>
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>

  <div class="modal-body">
    <p class="delete-text">{% trans 'Are you sure you want to delete object with label' %}
      <strong>{{ object.label }}</strong>?</p>
  </div>

  <div class="modal-footer">
    <button type="submit" id="delete-btn" class="btn btn-danger">{% trans 'Delete' %}</button>
  </div>

</form>

flexform/templates/flexform/filter_book.html
{% load widget_tweaks %}

<form method="post" action="">
  {% csrf_token %}

  <div class="modal-header">
    <h3 class="modal-title">Filter Books</h3>
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>


  <div class="modal-body">

    <div class="{% if form.non_field_errors %}invalid{% endif %} mb-2">
      {% for error in form.non_field_errors %}
        {{ error }}
      {% endfor %}
    </div>

    {% for field in form %}
      <div class="form-group">
        <label for="{{ field.id_for_label }}">{{ field.label }}</label>
        {% render_field field class="form-control" placeholder=field.label %}
        <div class="{% if field.errors %} invalid{% endif %}">
          {% for error in field.errors %}
            <p class="help-block">{{ error }}</p>
          {% endfor %}
        </div>
      </div>
    {% endfor %}
  </div>


  <div class="modal-footer">
    <input type="submit" class="btn btn-primary" name="clear" value="Clear"/>
    <button type="button" class="submit-btn btn btn-primary">Filter</button>
  </div>

</form>

flexform/templates/flexform/read_book.html
{% load widget_tweaks %}

<div class="modal-header">
  <h3 class="modal-title">Book details</h3>
  <button type="button" class="close" data-dismiss="modal" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button>
</div>

<div class="modal-body">

  <div class="">
    Title:
    {{ book.title }}
  </div>
  <div class="">
    Author:
    {{ book.author }}
  </div>
  <div class="">
    Price:
    {{ book.price }}
    €
  </div>
  <div class="">
    Pages:
    {{ book.pages }}
  </div>
  <div class="">
    Type:
    {{ book.get_book_type_display }}
  </div>
  <div class="">
    Publication date:
    {{ book.publication_date }}
  </div>

</div>

<div class="modal-footer">
  <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
</div>

flexform/templates/flexform/read_object.html
{% load widget_tweaks %}
{% load static %}
{% load i18n %}
<div class="modal-header">
  <h3 class="modal-title">{% trans 'Object' %} {% trans 'details' %}</h3>
  <button type="button" class="close" data-dismiss="modal" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button>
</div>

<div class="modal-body">

  <div class="">
    {% trans 'Label' %}:
    {{ object.label }}
  </div>
    <div class="">
    {% trans 'Description' %}:
    {{ object.description }}
  </div>
  <div class="">
     {% trans 'Type' %}:
   {% if object.type == 1 %}
                    <img src="{% static "open-iconic-master/svg/text.svg" %}" alt="Activated" width="15" height="15">
   {% else %}
                    <img src="{% static "open-iconic-master/svg/calculator.svg" %}" alt="Deactivated" width="15" height="15">
   {% endif %}
  </div>
  <div class="">
     {% trans 'Created by' %}:
    {{ object.created_by }}
  </div>
  <div class="">
      {% trans 'Created at' %}:
    {{ object.timestamp }}
  </div>

</div>

<div class="modal-footer">
  <button type="button" class="btn btn-default" data-dismiss="modal">{% trans 'Close' %}</button>
</div>

flexform/templates/flexform/signup.html
{% load widget_tweaks %}
{% load i18n %}
<form method="post" action="">
  {% csrf_token %}

  <div class="modal-header">
    <h3 class="modal-title">{% trans 'Sign up' %}</h3>
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>

  <div class="modal-body">

    <div class="{% if form.non_field_errors %}invalid{% endif %} mb-2">
      {% for error in form.non_field_errors %}
        {{ error }}
      {% endfor %}
    </div>

    {% for field in form %}
      <div class="form-group">
        <label for="{{ field.id_for_label }}">{{ field.label }}</label>
        {% render_field field class="form-control" placeholder=field.label %}
        <div class="{% if field.errors %} invalid{% endif %}">
          {% for error in field.errors %}
            <p class="help-block">{{ error }}</p>
          {% endfor %}
        </div>
      </div>
    {% endfor %}
  </div>

  <div class="modal-footer">
    <button type="button" class="submit-btn btn btn-secondary" style="background-color: #90323D;"  formnovalidate="formnovalidate">{% trans 'Sign up' %}</button>
  </div>

</form>

flexform/templates/flexform/update_book.html
{% load widget_tweaks %}

<form method="post" action="">
  {% csrf_token %}

  <div class="modal-header">
    <h3 class="modal-title">Update Book</h3>
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>

  <div class="modal-body">

    <div class="{% if form.non_field_errors %}invalid{% endif %} mb-2">
      {% for error in form.non_field_errors %}
        {{ error }}
      {% endfor %}
    </div>

    {% for field in form %}
      <div class="form-group">
        <label for="{{ field.id_for_label }}">{{ field.label }}</label>
        {% render_field field class="form-control" placeholder=field.label %}
        <div class="{% if field.errors %} invalid{% endif %}">
          {% for error in field.errors %}
            <p class="help-block">{{ error }}</p>
          {% endfor %}
        </div>
      </div>
    {% endfor %}
  </div>

  <div class="modal-footer">
    <button type="button" class="submit-btn btn btn-primary">Update</button>
  </div>

</form>

flexform/templates/flexform/update_form.html
{% load widget_tweaks %}
{% load crispy_forms_tags %}
{% load i18n %}
<form method="post" action="">
  {% csrf_token %}

  <div class="modal-header">
    <h3 class="modal-title">{% trans 'Update' %} {% trans 'Instance' %}</h3>
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>

  <div class="modal-body">

    <div class="{% if form.non_field_errors %}invalid{% endif %} mb-2">
      {% for error in form.non_field_errors %}
        {{ error }}
      {% endfor %}
    </div>
     {% crispy form %}
    <div class="{% if form.errors %} invalid{% endif %}">
          {% for error in form.errors %}
            <!--p class="help-block">{{ error }}</p-->
          {% endfor %}
    </div>

    <!--{% for field in form %}
      <div class="form-group">
        <label for="{{ field.id_for_label }}">{{ field.label }}</label>
        {% render_field field class="form-control" placeholder=field.label %}
        <div class="{% if field.errors %} invalid{% endif %}">
          {% for error in field.errors %}
            <p class="help-block">{{ error }}</p>
          {% endfor %}
        </div>
      </div>
    {% endfor %}-->
  </div>

  <div class="modal-footer">
    <button type="button" class="submit-btn btn btn-secondary"  style="background-color: #90323D;">{% trans 'Update' %}</button>
  </div>

</form>

flexform/templates/flexform/update_member.html
{% load widget_tweaks %}
{% load i18n %}
<form method="post" action="">
  {% csrf_token %}
{% load crispy_forms_tags %}
  <div class="modal-header">
    <h3 class="modal-title">{% trans 'Update' %} {% trans 'Member' %} {{ formmember.user }}</h3>
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>

  <div class="modal-body">

    <div class="{% if form.non_field_errors %}invalid{% endif %} mb-2">
      {% for error in form.non_field_errors %}
        {{ error }}
      {% endfor %}
    </div>
     {% crispy form %}
    <div class="{% if form.errors %} invalid{% endif %}">
          {% for error in form.errors %}
            <!--p class="help-block">{{ error }}</p-->
          {% endfor %}
    </div>
    <!--{% for field in form %}
      <div class="form-group">
        <label for="{{ field.id_for_label }}">{{ field.label }}</label>
        {% render_field field class="form-control" placeholder=field.label %}
        <div class="{% if field.errors %} invalid{% endif %}">
          {% for error in field.errors %}
            <p class="help-block">{{ error }}</p>
          {% endfor %}
        </div>
      </div>
    {% endfor %}-->
  </div>

  <div class="modal-footer">
    <button type="button" class="submit-btn btn btn-secondary"  style="background-color: #393e46; "  >{% trans 'Update' %}</button>
  </div>

</form>